const DIRECTION = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
};

export default [
  {
    key: 'akuma',
    name: 'akuma',
    img: require('images/thumbnails/akuma_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'alisa',
    name: 'alisa',
    img: require('images/thumbnails/alisa_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'asuka',
    name: 'asuka',
    img: require('images/thumbnails/asuka_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'bob',
    name: 'bob',
    img: require('images/thumbnails/bob_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'deviljin',
    name: 'deviljin',
    img: require('images/thumbnails/deviljin_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'dragunov',
    name: 'dragunov',
    img: require('images/thumbnails/dragunov_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'eddy',
    name: 'eddy',
    img: require('images/thumbnails/eddy_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'eliza',
    name: 'eliza',
    img: require('images/thumbnails/eliza_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'feng',
    name: 'feng',
    img: require('images/thumbnails/feng_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'gigas',
    name: 'gigas',
    img: require('images/thumbnails/gigas_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'heihachi',
    name: 'heihachi',
    img: require('images/thumbnails/heihachi_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'hwoarang',
    name: 'hwoarang',
    img: require('images/thumbnails/hwoarang_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'jack7',
    name: 'jack7',
    img: require('images/thumbnails/jack7_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'jin',
    name: 'jin',
    img: require('images/thumbnails/jin_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'josie',
    name: 'josie',
    img: require('images/thumbnails/josie_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'katarina',
    name: 'katarina',
    img: require('images/thumbnails/katarina_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'kazumi',
    name: 'kazumi',
    img: require('images/thumbnails/kazumi_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'kazuya',
    name: 'kazuya',
    img: require('images/thumbnails/kazuya_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'king',
    name: 'king',
    img: require('images/thumbnails/king_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'kuma',
    name: 'kuma',
    img: require('images/thumbnails/kuma_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'lars',
    name: 'lars',
    img: require('images/thumbnails/lars_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'law',
    name: 'law',
    img: require('images/thumbnails/law_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'lee',
    name: 'lee',
    img: require('images/thumbnails/lee_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'leo',
    name: 'leo',
    img: require('images/thumbnails/leo_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'lili',
    name: 'lili',
    img: require('images/thumbnails/lili_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'luckychloe',
    name: 'luckychloe',
    img: require('images/thumbnails/luckychloe_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'raven',
    name: 'Master Raven',
    img: require('images/thumbnails/raven_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'miguel',
    name: 'miguel',
    img: require('images/thumbnails/miguel_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'nina',
    name: 'nina',
    img: require('images/thumbnails/nina_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'panda',
    name: 'panda',
    img: require('images/thumbnails/panda_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'paul',
    name: 'paul',
    img: require('images/thumbnails/paul_thumbnail.png'),
    ss: DIRECTION.RIGHT,
  },
  {
    key: 'shaheen',
    name: 'shaheen',
    img: require('images/thumbnails/shaheen_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'steve',
    name: 'steve',
    img: require('images/thumbnails/steve_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'xiaoyu',
    name: 'xiaoyu',
    img: require('images/thumbnails/xiaoyu_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
  {
    key: 'yoshimitsu',
    name: 'yoshimitsu',
    img: require('images/thumbnails/yoshimitsu_thumbnail.png'),
    ss: DIRECTION.LEFT,
  },
];
